server:
  port: 8082
spring:
  application:
    name: z-coupon-service
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/z_coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: password
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志级别
logging:
  level:
    root: info
minio:
  endpoint: http://127.0.0.1:9000/
  accessKey: abcd
  secretKey: zhao1215

# seata 配置
seata:
  tx-service-group: ${spring.application.name}-group
  service:
    grouplist:
      z: 127.0.0.1:8091
    vgroup-mapping:
      z-coupon-service-group: z
rabbit:
  #交换机
  coupon-event-exchange: coupon.event.exchange
  #延迟队列，不能被监听消费
  coupon-release-delay-queue: coupon.release.delay.queue
  #延迟队列的消息过期后转发的队列
  coupon-release-queue: coupon.release.queue
  #进入延迟队列的路由key
  coupon-release-delay-routing-key: coupon.release.delay.routing.key
  #消息过期，进入释放死信队列的key
  coupon-release-routing-key: coupon.release.routing.key
  #消息过期时间,毫秒,测试改为15秒
  ttl: 15000