server:
  port: 8084
spring:
  application:
    name: z-order-service
  # nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/z_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: password
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志级别
logging:
  level:
    root: info
minio:
  endpoint: http://127.0.0.1:9000/
  accessKey: abcd
  secretKey: zhao1215
rabbit:
  order:
    #交换机
    event-exchange: order.event.exchange
    #延迟队列，不能被监听消费
    release-delay-queue: order.release.delay.queue
    #延迟队列的消息过期后转发的队列
    release-queue: order.release.queue
    #进入延迟队列的路由key
    release-delay-routing-key: order.release.delay.routing.key
    #消息过期，进入释放死信队列的key
    release-routing-key: order.release.routing.key
    #消息过期时间,毫秒,测试改为15秒
    ttl: 15000